server.port=8080

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8085/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}

# alumno-service
spring.cloud.gateway.server.webmvc.routes[0].id=alumno-service-route
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://alumno-service
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/alumnos/**

# curso-service
spring.cloud.gateway.server.webmvc.routes[1].id=curso-service-route
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://curso-service
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/cursos/**

# matricula-service
spring.cloud.gateway.server.webmvc.routes[2].id=matricula-service-route
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://matricula-service
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/matriculas/**

# docente-service
spring.cloud.gateway.server.webmvc.routes[3].id=docente-service-route
spring.cloud.gateway.server.webmvc.routes[3].uri=lb://docente-service
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/docentes/**

# Keycloak / OAuth 2.0
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/instituto