# Eureka para todos los servicios ejecutados en Docker
eureka.client.service-url.defaultZone=http://eureka-server:8085/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}